"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var MatchController_1 = require("../Controllers/MatchController");
var router = (0, express_1.Router)();
router.post('/', MatchController_1.createMatch);
router.get('/', MatchController_1.getMatch);
// router.get('/:id', getMatchById);
router.put('/:id', MatchController_1.updateMatch);
// router.delete('/:id', deleteMatch);
exports.default = router;
